### PR TITLE
Processes records messages according to PSR-3 rules

### PR DESCRIPTION
**Pull request by PetrHeinz**
Before:

image

After:

image

### CODE REVIEW

**Comment by landsman** [comment]
Thank you for debugging!

Somebody from community figure out "cleaner" solution I think: 
https://github.com/symfony/symfony/discussions/57747#discussioncomment-10076309

So it can be done by just one service.

**Comment by PetrHeinz** [comment]
Hi @landsman, always happy to help 🙌

Thanks for linking that.

I wouldn't call the linked solution cleaner per-se, it does the exact same thing, only via code instead of DIC configuration. Both just register the PSR3 processor.

**Comment by landsman** [comment]
Yep, my goal is to create package (vendor) which I can install on every projects without much configuration (just bettertack token, logger levels and that's it).

**Comment by PetrHeinz** [comment]
@landsman Thanks for sharing that, understand 👍 

Did you know that you can create sources in Better Stack programmatically via [Source API](https://betterstack.com/docs/logs/api/create-a-source/) and a [Terraform provider](https://github.com/BetterStackHQ/terraform-provider-logtail)? This might help with your use-case nicely 🙌

**Comment by landsman** [comment]
Very nice! I love that!

**Pull request closed without merging**
